version: '3.9'

services:
  backend: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    env_file:
      - .env