version: '3.9'

services:
  backend: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:3.6
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: myapp
    networks:
      - backend

networks:
  backend:
volumes:
  mongodb_data: